# Generated by Django 3.1.3 on 2021-04-04 04:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_counter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreetLanes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('x_1', models.FloatField()),
                ('y_1', models.FloatField()),
                ('x_2', models.FloatField()),
                ('y_2', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='VehicleLanes',
        ),
        migrations.RemoveField(
            model_name='vehicleassessmentconfiguration',
            name='id_type',
        ),
        migrations.RemoveField(
            model_name='vehicleassessmentconfiguration',
            name='x_1',
        ),
        migrations.RemoveField(
            model_name='vehicleassessmentconfiguration',
            name='x_2',
        ),
        migrations.RemoveField(
            model_name='vehicleassessmentconfiguration',
            name='y_1',
        ),
        migrations.RemoveField(
            model_name='vehicleassessmentconfiguration',
            name='y_2',
        ),
        migrations.AddField(
            model_name='vehicleassessmentconfiguration',
            name='detection_roi',
            field=models.TextField(default='[              {                       "y":0.4,                "x":0.4            },            {                "y":0.4,                "x":0.9            },            {                "y":0.9,                "x":0.9            },            {                "y":0.9,                "x":0.4            }        ]'),
        ),
        migrations.AlterField(
            model_name='vehicletypes',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
