# Generated by Django 3.1.3 on 2021-04-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_counter', '0002_auto_20210403_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletypes',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
