# Generated by Django 3.1.3 on 2021-04-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_counter', '0003_auto_20210406_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletypes',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
